build:
  project: build3/vs2010/0_Bullet3Solution.sln

build_script:
  - mkdir cmake
  - cd cmake
  - cmake .. -G"Visual Studio 14 2015 Win64"
  - cmake --build . --target ALL_BUILD --config Release -- /maxcpucount:4 /verbosity:quiet

test_script:
  - ctest --parallel 4 --build-config Release --output-on-failure

before_build:
  - echo %CD%
  - ps: cd build3
  - echo %CD%
  - premake4  vs2010
  - ps: cd ..

